In [1]:
import numpy as np
import pandas as pd

In [4]:
data_list=[['bablu',20 ,'noida',15000],
           ['raju', 19	,'nainital',100],
           ['urmi',	20,'dc',20],
           [ 'hema',20,'haldwani',22]]
columns=['name','age','city','salary']
df=pd.DataFrame(data_list,columns=columns)
df

    name  age      city  salary
0  bablu   20     noida   15000
1   raju   19  nainital     100
2   urmi   20        dc      20
3   hema   20  haldwani      22

In [5]:
#conditinal  selection

In [6]:
df[df['age']>19]

    name  age      city  salary
0  bablu   20     noida   15000
2   urmi   20        dc      20
3   hema   20  haldwani      22

In [7]:
df

    name  age      city  salary
0  bablu   20     noida   15000
1   raju   19  nainital     100
2   urmi   20        dc      20
3   hema   20  haldwani      22

In [16]:
df[(df['salary'] >22 ) & (df['city']=="noida")]

    name  age   city  salary
0  bablu   20  noida   15000