In [3]:
import numpy as np
import pandas as pd

In [14]:
df1=pd.DataFrame({
    'name':['raju','bablu','urmi','hema']
},index=[1,2,3,4])

df2=pd.DataFrame({
    'score':[80,90,100,110]},index=[2,3,4,5])

In [15]:
df1

    name
1   raju
2  bablu
3   urmi
4   hema

In [16]:
df2

   score
2     80
3     90
4    100
5    110

In [13]:
df1.join (df2)

    name  score
1   raju     80
2  bablu     90
3   urmi    100
4   hema    110

In [23]:
df1.join (df2)

    name  score
1   raju    NaN
2  bablu   80.0
3   urmi   90.0
4   hema  100.0

In [22]:
df1.join(df2,how="outer")

    name  score
1   raju    NaN
2  bablu   80.0
3   urmi   90.0
4   hema  100.0
5    NaN  110.0

In [ ]:
df1.join(df2,how='')