In [1]:
import numpy as np
import pandas as pd

In [2]:
#merging 2 data frames

In [17]:
#dataframe1
employees=pd.DataFrame({
    'employees_id':[1,2,3,4,5],
    'name':['bablu','raju','urmi','abhishek','hema'],
    'department':['hr','IT','finance','IT','hr']
})

#dataframe2
salaries=pd.DataFrame({
    'employees_id':[1,2,3,6,7],
    'salary':[60000,55000,80000,90000,50000],
    'bonus':[5000,6000,5500,8000,4000]
})

In [18]:
employees

   employees_id      name department
0             1     bablu         hr
1             2      raju         IT
2             3      urmi    finance
3             4  abhishek         IT
4             5      hema         hr

In [13]:
salaries

   employees_id  salary  bonus
0             1   60000   5000
1             2   55000   6000
2             3   80000   5500
3             6   90000   8000
4             7   50000   4000

In [20]:
pd.merge(employees,salaries)

   employees_id   name department  salary  bonus
0             1  bablu         hr   60000   5000
1             2   raju         IT   55000   6000
2             3   urmi    finance   80000   5500

In [ ]:
#on lagana hogaa

In [21]:
pd.merge(employees,salaries,on ='employees_id')

   employees_id   name department  salary  bonus
0             1  bablu         hr   60000   5000
1             2   raju         IT   55000   6000
2             3   urmi    finance   80000   5500

In [22]:
pd.merge(employees,salaries,on ='employees_id',how='inner')

   employees_id   name department  salary  bonus
0             1  bablu         hr   60000   5000
1             2   raju         IT   55000   6000
2             3   urmi    finance   80000   5500

In [23]:
#yyeh yeh kaam krta h employees id ke base pr common data ko merge kr detaa h

In [ ]:
#outer

In [24]:
pd.merge(employees,salaries,on ='employees_id',how='outer')

   employees_id      name department   salary   bonus
0             1     bablu         hr  60000.0  5000.0
1             2      raju         IT  55000.0  6000.0
2             3      urmi    finance  80000.0  5500.0
3             4  abhishek         IT      NaN     NaN
4             5      hema         hr      NaN     NaN
5             6       NaN        NaN  90000.0  8000.0
6             7       NaN        NaN  50000.0  4000.0

In [ ]:
#outer columns se hisab se merge karne kaa  kaam karte haii

In [25]:
#left ka use karenege pahli wali(employees ) wali table le liyee us ke baiss par data merge hogaa

In [28]:
pd.merge(employees,salaries,on='employees_id',how='left')

   employees_id      name department   salary   bonus
0             1     bablu         hr  60000.0  5000.0
1             2      raju         IT  55000.0  6000.0
2             3      urmi    finance  80000.0  5500.0
3             4  abhishek         IT      NaN     NaN
4             5      hema         hr      NaN     NaN

In [30]:
pd.merge(employees,salaries,on='employees_id',how='right')

   employees_id   name department  salary  bonus
0             1  bablu         hr   60000   5000
1             2   raju         IT   55000   6000
2             3   urmi    finance   80000   5500
3             6    NaN        NaN   90000   8000
4             7    NaN        NaN   50000   4000

In [ ]:
#right ka kaam right