In [2]:
import numpy as np
import pandas as pd

In [15]:
data={
    'a':[1,2,np.nan,4,5],
    'b':[1,2,3,4,5],
    'c':[1,2,3,np.nan,np.nan],
    'd':[1,np.nan,np.nan,np.nan,5]
}
df=pd.DataFrame(data)
df

     a  b    c    d
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [ ]:
#finding  missing data

In [7]:
df.isna()

       a      b      c      d
0  False   True  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [8]:
df.isna().sum()

a    1
b    1
c    2
d    3
dtype: int64

In [10]:
df.isna().any()

a    True
b    True
c    True
d    True
dtype: bool

In [11]:
#remove missing data

In [12]:
df

     a    b    c    d
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [13]:
df.dropna()

Empty DataFrame
Columns: [a, b, c, d]
Index: []

In [ ]:
#sabko isliye hata diya hai kyunki sab maii nan vakue thi  agar is chij se bachnan hai to nichee...

In [16]:
df

     a  b    c    d
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [17]:
#then  yaha par ham ab remove kare mssing data ko sirf ak column reh jayye ga orr baaki rows ssab hat jayegi jismaii missing  dtaa hai

In [19]:
df.dropna()

     a  b    c    d
0  1.0  1  1.0  1.0

In [22]:
#thresh ka use  ham dropnake sath remove karne ke liye use krte hai mtlb hame jjitni need hai jaise mai kah ra hhunn ki mujhe 2 missing se jyada alw data ko remove karna hai to yaha pr isa use karenege okayyy

In [21]:
df

     a  b    c    d
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [23]:
df.dropna(thresh=3)

     a  b    c    d
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [25]:
df.dropna(thresh=4)

     a  b    c    d
0  1.0  1  1.0  1.0

In [26]:
df.dropna(thresh=5)

Empty DataFrame
Columns: [a, b, c, d]
Index: []

In [27]:
#filling the missing values

In [28]:
df

     a  b    c    d
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [31]:
df.fillna(0)

     a  b    c    d
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [32]:
# now i want  to fill the values  in each columns like ...

In [34]:
values={'a':10,'b':100,'c':200,'d':300}
df.fillna(value=values)

      a  b      c      d
0   1.0  1    1.0    1.0
1   2.0  2    2.0  300.0
2  10.0  3    3.0  300.0
3   4.0  4  200.0  300.0
4   5.0  5  200.0    5.0

In [35]:
#jaha par bhi nan values thi waha pe hamnani apne according values fill kar di hai