In [1]:
import numpy as np

In [2]:
import pandas as  pd

In [ ]:
#“A DataFrame is a two-dimensional, tabular data structure provided by Pandas. 
#It consists of rows and columns, similar to an Excel spreadsheet or a SQL table. We use DataFrames to store,
#manipulate, clean, filter, and analyze structured data.”

In [4]:
data={
    'name':['bablu','raju','urmi','hema'],
    'age':[20,19,20,20],
    'city':['noida','nainital','dc','haldwani'],
    'salary':[15000,100,20,22]
}

In [8]:
df=pd.DataFrame(data)

In [9]:
df

    name  age      city  salary
0  bablu   20     noida   15000
1   raju   19  nainital     100
2   urmi   20        dc      20
3   hema   20  haldwani      22

In [12]:
data_list=[['bablu',20 ,'noida',15000],
           ['raju', 19	,'nainital',100],
           ['urmi',	20,'dc',20],
           [ 'hema',20,'haldwani',22]]

In [20]:
df2=pd.DataFrame(data_list)
df2

       0   1         2      3
0  bablu  20     noida  15000
1   raju  19  nainital    100
2   urmi  20        dc     20
3   hema  20  haldwani     22

In [15]:
#yaha par headr  matalab jo columns ke naam h vo nhi hain to is problem ko solve karne ke liye ham columns ka use karenge

In [22]:
data_list=[['bablu',20 ,'noida',15000],
           ['raju', 19	,'nainital',100],
           ['urmi',	20,'dc',20],
           [ 'hema',20,'haldwani',22]]
columns=['name','age','city','salary']
df2=pd.DataFrame(data_list,columns=columns)
df2

    name  age      city  salary
0  bablu   20     noida   15000
1   raju   19  nainital     100
2   urmi   20        dc      20
3   hema   20  haldwani      22