In [2]:
import numpy as np
import pandas as pd

In [5]:
data_list=[['bablu',20 ,'noida',15000],
           ['raju', 19	,'nainital',100],
           ['urmi',	20,'dc',20],
           [ 'hema',20,'haldwani',22]]
columns=['name','age','city','salary']
df2=pd.DataFrame(data_list,columns=columns)
df2

    name  age      city  salary
0  bablu   20     noida   15000
1   raju   19  nainital     100
2   urmi   20        dc      20
3   hema   20  haldwani      22

In [9]:
df2['name']

0    bablu
1     raju
2     urmi
3     hema
Name: name, dtype: str

In [10]:
df2['salary']

0    15000
1      100
2       20
3       22
Name: salary, dtype: int64

In [11]:
df2[['name','age','salary']]

    name  age  salary
0  bablu   20   15000
1   raju   19     100
2   urmi   20      20
3   hema   20      22

In [ ]:
#add a new columnn/.....?

In [12]:
df2['designation']=['doctor','engineer','teacher','army']

In [13]:
df2

    name  age      city  salary designation
0  bablu   20     noida   15000      doctor
1   raju   19  nainital     100    engineer
2   urmi   20        dc      20     teacher
3   hema   20  haldwani      22        army

In [14]:

#remove columns ya column..okay ..?

In [17]:
df2.drop('designation',axis=1)

    name  age      city  salary
0  bablu   20     noida   15000
1   raju   19  nainital     100
2   urmi   20        dc      20
3   hema   20  haldwani      22

In [18]:
#isnaii main ram se data nhi hatatya hai sirf uski copy bana di hai ye is type ka dikhega karke .. agr mai ab yaha par again df2 ko 
#print karau to output kuch is type ka aayega @

In [19]:
df2

    name  age      city  salary designation
0  bablu   20     noida   15000      doctor
1   raju   19  nainital     100    engineer
2   urmi   20        dc      20     teacher
3   hema   20  haldwani      22        army

In [21]:
#yaha par desgination hai vo nhi hata usko hatanai ke liye hame karna padega ..?
#inplace kaa use karna padega

In [26]:
df2.drop('designation',axis=1,inplace= True)

In [27]:
df2

    name  age      city  salary
0  bablu   20     noida   15000
1   raju   19  nainital     100
2   urmi   20        dc      20
3   hema   20  haldwani      22

In [29]:
#hamnai yaha par axis use kya axis=1 kiya iska matlb hua ki ham column name jisko hame selet karna hhai hatani ke liye fir inplace

In [30]:
#ka use karke ham parmanetly hata denge agar sirf ham  drop kare to in place fucntion ka usen  n kare to nhhi hatega .. oak ham axis 
#=o karke bhi  kar sakte hai is se jo hmari rows ka data hatna hai po hat jayega okayyyy....

In [31]:
df2.drop(2,axis=0)

    name  age      city  salary
0  bablu   20     noida   15000
1   raju   19  nainital     100
3   hema   20  haldwani      22

In [32]:
df2

    name  age      city  salary
0  bablu   20     noida   15000
1   raju   19  nainital     100
2   urmi   20        dc      20
3   hema   20  haldwani      22

In [33]:
#or yaaha par ham ak list banakar 2 se jyada ya any column remove kr sakte haiiii..?

In [40]:
df2.drop(['name','age'],axis=1)

       city  salary
0     noida   15000
1  nainital     100
2        dc      20
3  haldwani      22

In [41]:
df2

    name  age      city  salary
0  bablu   20     noida   15000
1   raju   19  nainital     100
2   urmi   20        dc      20
3   hema   20  haldwani      22

In [ ]:

#selecting rows

In [42]:
df2

    name  age      city  salary
0  bablu   20     noida   15000
1   raju   19  nainital     100
2   urmi   20        dc      20
3   hema   20  haldwani      22

In [45]:
df2.loc[0]

name      bablu
age          20
city      noida
salary    15000
Name: 0, dtype: object

In [ ]:
#loc ko ham rows select karne ke liye use karte hai okay loc yaha par location bata ta hai rows ki

In [46]:
#or ha  ham bahut saari rows ko ak sath delete kar sakte hai

In [47]:
df2.loc[[0,2]]

    name  age   city  salary
0  bablu   20  noida   15000
2   urmi   20     dc      20

In [48]:
#inloc ka use ham index se rows ke data found karte hain

In [51]:
df2.iloc[2]

name      urmi
age         20
city        dc
salary      20
Name: 2, dtype: object

In [ ]:

#selecting subset of rows column

In [52]:
df2

    name  age      city  salary
0  bablu   20     noida   15000
1   raju   19  nainital     100
2   urmi   20        dc      20
3   hema   20  haldwani      22

In [ ]:
#yaha par mujhe nainital 10
#                dc       20

In [54]:
df2.loc[[1,2]][['city','salary']]

       city  salary
1  nainital     100
2        dc      20